services:
  threemix:
    container_name: threemix
    depends_on:
      - db
    build: ../
    develop:
      watch:
        - action: sync
          path: ../src
          target: /app/src
    security_opt:
      - no-new-privileges:true
    environment:
      DB_HOST: db
      COOKIE_DOMAIN: localhost:5173
      PUBLIC_HOST: "0.0.0.0" # Internal to the container, it should be on all interfaces
    networks:
        - threemix
    ports:
      - 127.0.0.1:8080:8080
  
  db:
    image: postgres
    container_name: threemixDB
    environment:
      POSTGRES_PASSWORD: passwd
    ports:
      - 127.0.0.1:5432:5432
    security_opt:
      - no-new-privileges:true
    
    # Switch attach to true to get DB logging.
    attach: false
    networks:
        - threemix

networks:
    threemix:
